name: tu_rfid_attendance
description: TU RFID Attendance
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  shared_preferences: ^0.5.6+1
  http: ^0.12.0+4
  fluttertoast: ^3.1.3
  pk_skeleton: ^0.0.2
  pin_code_fields: ^2.3.0+3

#dependency_overrides:
#  intl: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/images/logo.jpg
    - assets/images/header.jpg
    - assets/images/header_home.png
    - assets/images/splashbackground.jpg

  fonts:
    - family: JFFlat
      fonts:
        - asset: assets/fonts/jf_flat_regular.ttf
          weight: 700

